invites = ['Michael', 'Fábio', 'Bruno']
print('Olá '+invites[0]+', gostaria de convida-lo a um jantar')
print('Olá '+invites[1]+', gostaria de convida-lo a um jantar')
print('Olá '+invites[2]+', gostaria de convida-lo a um jantar')
print('Infelizmente Fábio não comparecerá')
invites[1] = 'Mike'
print('Olá '+invites[0]+', gostaria de convida-lo a um jantar')
print('Olá '+invites[1]+', gostaria de convida-lo a um jantar')
print('Olá '+invites[2]+', gostaria de convida-lo a um jantar')
print("Encontrei umma mesa de jantar maior e irei convidar mais pessoasm")
invites.insert(0, 'Bob')
invites.insert(3, 'Honey')
invites.append('Greg')
print('Olá, passando aqui para convida-lo '+invites[0]+' para meu jantar')
print('Olá, passando aqui para convida-lo '+invites[1]+' para meu jantar')
print('Olá, passando aqui para convida-lo '+invites[2]+' para meu jantar')
print('Olá, passando aqui para convida-lo '+invites[3]+' para meu jantar')
print('Olá, passando aqui para convida-lo '+invites[4]+' para meu jantar')
print('Olá, passando aqui para convida-lo '+invites[5]+' para meu jantar')